version: '3'

services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    volumes:
      - .:/source/
      - static_volume:/source/staticfiles/
      - media_volume:/source/mediafiles/
    working_dir: /source/
    command: gunicorn settings.wsgi --bind 0.0.0.0:8000

    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    image: postgres:latest
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
  nginx:
      build: ./nginx
      volumes:
          - static_volume:/source/staticfiles/
          - media_volume:/source/mediafiles/
      ports:
          - 1337:80
      depends_on:
          - app

volumes:
  postgres_data:
  static_volume:
  media_volume:
